apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/dragoonsbets/drgbffweb:{{.VERSION}}"
  artifacts:
  - imageName: drgbffweb
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/dragoonsbets/drgbffweb:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: drgbffweb
        chartPath: charts/drgbffweb
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/dragoonsbets/drgbffweb"
          image.tag: "{{.DIGEST_HEX}}"